services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-test.butal.ru}
    volumes:
      - wordpress_data:/var/www/html
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt      
    networks:
      - internal

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-test.butal.ru}
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER:-admin}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD:-admin12345}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL:-admin@example.com}
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - internal

  mariadb:
    build: ./mariadb
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_conf:/etc/letsencrypt
    networks:
      - internal      

volumes:
  wordpress_data:
  mariadb_data:
  certbot_www:
  certbot_conf:

networks:
  internal:
    driver: bridge