- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - git
      - curl
      - gnupg
    update_cache: yes

- name: Install Docker dependencies
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    update_cache: yes

- name: Enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Clone project
  git:
    repo: "{{ repo_url }}"
    dest: "{{ project_dir }}"
    force: yes