- name: Start WordPress
  shell: |
    cd {{ project_dir }}
    docker compose up -d wordpress

- name: Wait for WordPress container is up
  include_tasks: "../common/tasks/wait_for_container.yml"
  vars:
    container_name: wordpress
