mysql_root_password: rootpassword
mysql_database: wordpress
mysql_user: wpuser
mysql_password: wppassword

wordpress_admin_user: sskobyak
wordpress_admin_password: sskobyak1234
wordpress_admin_email: admin@example.com
