- name: Start nginx only (HTTP bootstrap)
  shell: |
    cd {{ project_dir }}
    docker compose up -d --build nginx

- name: Wait for nginx container is up
  include_tasks: "../common/tasks/wait_for_container.yml"
  vars:
    container_name: nginx

- name: Wait for nginx HTTP
  uri:
    url: http://127.0.0.1
    follow_redirects: none
    status_code:
      - 200
      - 301
  register: nginx_http_result
  changed_when: false
  retries: 10
  delay: 3
  until: nginx_http_result.status in [200, 301]
