- name: Start nginx only (HTTP bootstrap)
  shell: |
    cd {{ project_dir }}
    docker compose up -d nginx

- name: Wait for nginx HTTP
  uri:
    url: http://{{ domain }}
    status_code: 200
  register: nginx_http_result
  retries: 10
  delay: 3
  until: nginx_http_result.status == 200
