- name: Cloud-1 deployment
  hosts: cloud
  become: true

  vars_files:
    - group_vars/cloud/vault.yml

  vars:
    project_dir: /home/cloud
    domain: test.butal.ru
    repo_url: "https://github.com/sergscob/cloud1.git"

  roles:
    - role: common
      tags: common

    - role: mariadb
      tags: mariadb

    - role: wordpress
      tags: wordpress

    - role: phpmyadmin
      tags: phpmyadmin

    - role: nginx
      tags: nginx

    - role: certbot
      tags: certbot
