- name: Cloud-1 full deployment (staged bootstrap)
  hosts: cloud
  become: true

  vars:
    project_dir: /home/cloud
    domain: test.butal.ru
    repo_url: "https://github.com/sergscob/cloud1.git"

  roles:
    - common
    - mariadb
    - wordpress
    - phpmyadmin
    - nginx
    - certbot_tls