- name: Start phpMyAdmin
  shell: |
    cd {{ project_dir }}
    docker compose up -d phpmyadmin

- name: Wait for phpMyAdmin container is up
  include_tasks: "../common/tasks/wait_for_container.yml"
  vars:
    container_name: phpmyadmin
